{{- if .Values.restoreDatabase }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "post-upgrade-hook1"
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "post-upgrade-hook1"
    spec:
      containers:
      - name: mongoutil-mongorestore
        image: bitnami/mongodb
        command: ["mongorestore", "--drop", "--host", "{{ .Release.Name }}-mongodb"  , "--username", "{{ .Values.mongodb.mongodbUsername }}", "--password", "{{ .Values.mongodb.mongodbPassword }}", "--db", "{{ .Values.mongodb.mongodbDatabase }}" , "--archive=/dump/rocketchat-db-bkup.gz", "--gzip"]
        volumeMounts:
        - mountPath: "/dump"
          name: mongodump
      volumes:
      - name: mongodump
        persistentVolumeClaim:
          claimName: rocketchat-mongodump
      restartPolicy: Never
  backoffLimit: 7 
{{- end }}
